use [tankwars]

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME = 'Items' AND COLUMN_NAME = 'type')
BEGIN
 ALTER TABLE dbo.Items ADD
  type int NOT NULL CONSTRAINT DF_Items_type DEFAULT 0
END